using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using SuperTiled2Unity;

namespace CameraControl
{
    public class SetMapBorders : MonoBehaviour
    {
        Dictionary<string, Direction> directionMap = new Dictionary<string, Direction>()
        {
            { "top", Direction.Top },
            { "bottom", Direction.Bottom },
            { "left", Direction.Left },
            { "right", Direction.Right }
        };

        // Start is called before the first frame update
        // Apply this script to any TiledObjectlayer that needs to have world boundaries set
        void Start()
        {
            // Iterate over all the children of the MapBorder layer
            // This should only have objects generated by Tiled
            foreach (var child in GetComponentsInChildren<Transform>())
            {
                // Each border should have property denoting the side of the world it is located
                var tiledProperties = child.GetComponent<SuperCustomProperties>().m_Properties;
                foreach (var property in tiledProperties)
                {
                    if ("position" == property.m_Name)
                    {
                        var direction = directionMap[property.m_Value];
                        // These objects already have a collider on them
                        // Add a collider trigger to each child and enable isTrigger
                        child.gameObject.AddComponent<RoomCameraBorder>().direction = direction;
                        child.GetComponent<EdgeCollider2D>().isTrigger = true;
                    }

                }
            }
        }

    }
}